spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: ${MYSQL_HOST_PORT}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1h


file:
  dir: ${file_dir}
